package modelos;
import java.awt.Point;
import java.io.Serializable;

import javax.swing.Icon;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Celula.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class Celula extends Point implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 7L;
	boolean acertada;
	boolean selecionada;
	Icon icone;
	
	public Celula(int x,int y){
		super(x,y);
		aTipoCelula = TipoCelula.Agua;
		acertada = false;
		
	}
	
	public TipoCelula aTipoCelula;
	
	public TipoCelula getTipoCelula() {
		return this.aTipoCelula;
	}
	
	public void setTipoCelula(TipoCelula tipoCelula) {
		aTipoCelula = tipoCelula;
	}
	public void acertar(){
		acertada = true;
	}
	public boolean isAtirada(){
		return acertada;
	}
	public boolean isSelecionada() {
		return selecionada;
	}

	public void setSelecionada(boolean selecionada) {
		this.selecionada = selecionada;
	}

	public void carregarImagem(TipoCelula tipoCelula) {
		//TODO: Rever esta implementação, verificar na doc.
	}

	public void limpar() {
		this.aTipoCelula = TipoCelula.Agua;
		this.acertada = false;
	}
	
	public void setIcone(Icon icone){
		this.icone = icone;
	}
	public Icon getIcone(){
		return this.icone;
	}
	public boolean hasIcone(){
		return this.icone != null;
	}
}
