package modelos;

import Comunicacao.Constantes;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Conexao.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class Conexao {
	private String sIp_servidor;
	private int porta_servidor;
	Jogador player;
	
	
	public Conexao(Jogador jogador){
		player = jogador;
		sIp_servidor = Constantes.SERVER_ADDRESS;
		porta_servidor = Constantes.SERVER_PORT;
	}
	public void conectarJogador() {
		if(player.isOnline())
			return;
		
	}
	
	public void desconectarJogador() {
		if(!player.isOnline())
			return;
	}
	
	public void enviarAtaque(Celula celulaAtacada) {
		
	}
	
	public void receberAtaque() {
	
	}
	
	public void enviarVitoria(Jogador jogador) {
	
	}
	
	public void receberVitoria() {
	
	}
	
	public void enviarAcao(String comando) {
	
	}
	
	public void receberAcao() {
	
	}
}
