package modelos;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Ranking.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class Ranking {
	public Usuario[] aListaUsuario;
	
	public Usuario[] getListaUsuario() {
	 return aListaUsuario;
	}
	
	public void setListaUsuario(Usuario[] usuarios) {
		aListaUsuario = usuarios;
	}
}
