package modelos;

import java.io.Serializable;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : TipoCelula.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public enum TipoCelula implements Serializable {
	Embarcacao(1),
	Agua(2),
	AreaLivre(3);
	
	private static final long serialVersionUID = 9L;
	
	private int value;
	TipoCelula(int valor){
		this.value = valor;
	}
}
