package modelos;
import java.util.Random;
import java.util.Stack;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Bot.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando,@Marcus
//
//




public class Bot extends Jogador {
	Tabuleiro oTabuleiroVirtual;
	Celula oUltimaCelulaAtacada;
	Celula oProximaCelula;
	boolean bAcertouEmbarcacao = false;
	boolean bAfundouEmbarcacao = false;

	//pilha de jogadas feitas para fins heuristicos de jogada
	Stack<Celula> celulasEscolhidas;
	
	public Tabuleiro getTabuleiroVirtual() {
		return this.oTabuleiroVirtual;
	}
	
	public void setTabuleiroVirtual(Tabuleiro objTabuleiro) {
		this.oTabuleiroVirtual = objTabuleiro;
	}
	
	public Celula getUltimaCelulaAtacada() {
		return this.oUltimaCelulaAtacada;
	}
	
	public void setUltimaCelulaAtacada(Celula objCelula) {
		this.oUltimaCelulaAtacada = objCelula;
	}
	
	public Celula getProximaCelula() {
		return this.oProximaCelula;
	}
	
	public void setProximaCelula(Celula objCelula) {
		this.oProximaCelula = objCelula;
	}
	
	public boolean acertouEmbarcacao() {
		return bAcertouEmbarcacao;
	}

	public void acertouEmbarcacao(boolean bAcertouEmbarcacao) {
		this.bAcertouEmbarcacao = bAcertouEmbarcacao;
	}

	public boolean afundouEmbarcacao() {
		return bAfundouEmbarcacao;
	}

	public void afundouEmbarcacao(boolean bAfundouEmbarcacao) {
		this.bAfundouEmbarcacao = bAfundouEmbarcacao;
	}

	public Celula getUltimaEscolha() {
		//retira a ultima jogada da pilha
		return celulasEscolhidas.pop();
	}

	public void setCelulasEscolhida(Celula celulasEscolhida) {
		//Insere a jogada na pilha
		this.celulasEscolhidas.push(celulasEscolhida);
	}

	public void analisarTabuleiro() {
		if (bAcertouEmbarcacao && !bAfundouEmbarcacao) {
			Celula atacada = getUltimaCelulaAtacada();
			//TODO: Pensar no algoritmo do bot para realizar ataques
			
		}
	}
	
	public void analisarJogada() {
	
	}
	
	public Celula atacar() {
		Celula celulaAtacada = new Celula();
		
		return celulaAtacada;
	}
	
	//TODO: Associar esta provocação para enviar no chat(se tiver)
	public String provocar() {
	
		String[] listaProvocacoes = {
				"Você não é páreo para a minha ira!",
				"Não terá trégua este jogo!",
				"Achei que você seria um oponente formidável... que decepção!",
				"Erm, acho que você... ah, deixa pra lá.",
				"Cuidado que eu to chegando!",
				"Virei, cruzei, atirei e... marquei!",
				"Os sete mares estão com os dias contados",
				"Conhece o mar-morto? Foi eu quem ajudou a matar >:)"
				};
		
		Random rand = new Random();
		int indexProvocacao = rand.nextInt(listaProvocacoes.length);
		
		return listaProvocacoes[indexProvocacao];
	}
}
