package modelos;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Estatisticas.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//

import java.util.*;


public class Estatistica {
	public void mediaPontuacaoPorJogo() {
	
	}
	
	public void cadastrosPeriodo(Date dataIni, Date dataFim) {
	
	}
	
	public void usuariosAtivos() {
	
	}
	
	public void usuariosPorPais(String pais) {
	
	}
	
	public void jogosJogados(int idUsuario) {
	
	}
}
