package modelos;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Sons.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class Sons {
	public String sLocalSom;
	public boolean bRepetir;
	public void getLocalSom() {
	
	}
	
	public void setLocalSom(String localSom) {
	
	}
	
	public void getRepetir() {
	
	}
	
	public void setRepetir(boolean repetir) {
	
	}
	
	public void tocarSom() {
	
	}
}
