//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : BancoDeDados.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class BancoDeDados {
	public String sSqlDriver;
	public String sSqlPath;
	public String sUsuario;
	public String sSenha;
	
	public void conectarBanco() {
	
	}
	
	public void abrirConexao() {
	
	}
	
	public void fecharConexao() {
	
	}
}
