//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Conexao.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//

public class Conexao {
	public String sIp_servidor;

	public void conectarJogador(String ip) {

	}

	public void desconectarJogador(Objeto Jogador) {

	}

	public void enviarAtaque(Objeto Celula) {

	}

	public void receberAtaque() {

	}

	public void enviarVitoria(Objeto Jogador) {

	}

	public void receberVitoria() {

	}

	public void enviarAcao(String comando) {

	}

	public void receberAcao() {

	}
}
