//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Jogador.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class Jogador {
	public int iId_usuario;
	public boolean bStatusJogador;
	public String sIp_jogador;
	public boolean bIsBot;
	public int iPontuacao;
	public Objeto Tabuleiro oTabuleiroAtaque;
	public Objeto Tabuleiro oTabuleiroDefesa;
	public void getId_usuario() {
	
	}
	
	public void setId_usuario(int idUsuario) {
	
	}
	
	public void getStatusJogador() {
	
	}
	
	public void setStatusJogador(boolean statusJogador) {
	
	}
	
	public void getIp_jogador() {
	
	}
	
	public void setIp_jogador(String ipJogador) {
	
	}
	
	public void getIsBot() {
	
	}
	
	public void setIsBot(boolean isBot) {
	
	}
	
	public void getPontuacao() {
	
	}
	
	public void setPontuacao(int pontuacao) {
	
	}
	
	public void getTabuleiroAtaque() {
	
	}
	
	public void setTabuleiroAtaque(Objeto Tabuleiro) {
	
	}
	
	public void getTabuleiroDefesa() {
	
	}
	
	public void setTabuleiroDefesa(Objeto Tabuleiro) {
	
	}
	
	public void isOnLine(int id_usuario) {
	
	}
	
	public void setOffline() {
	
	}
	
	public void setOnline() {
	
	}
	
	public void seJogando(boolean seJogando) {
	
	}
}
