//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Jogo.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//

import java.util.*;


public class Jogo {
	public int iCodJogadorVencedor;
	public Array Objeto Jogador aListaJogador;
	public boolean bJogoEncerrado;
	public Date DataCriacaoJogo;
	public void getCodJogadorVencedor() {
	
	}
	
	public void setCodJogadorVencedor(int codJogadorVencedor) {
	
	}
	
	public void getListaJogador() {
	
	}
	
	public void setListaJogador(Array Objeto Jogador) {
	
	}
	
	public void getJogoEncerrado() {
	
	}
	
	public void setJogoEncerrado(boolean jogoEncerrado) {
	
	}
	
	public void getDataCriacaoJogo() {
	
	}
	
	public void setDataCriacaoJogo(Date dataCriacaoJogo) {
	
	}
	
	public void iniciarJogo() {
	
	}
	
	public void conectarJogador(Objeto Jogador) {
	
	}
	
	public void gerarJogo() {
	
	}
	
	public void sePingarJogador(Objeto Jogador) {
	
	}
	
	public void encerrarJogo() {
	
	}
	
	public void aturarEm(Objeto Jogador, Objeto Celula) {
	
	}
}
