//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Regras.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class Regras {
	public void validarPosicaoNavio(Embarcacao objEmbarcacao, Tabuleiro objTabuleiro) {
	
	}
	
	public void validarTiro(Celula objCelula, Tabuleiro objTabuleiro) {
	
	}
	
	public void verificarVencedor(Tabuleiro objTabuleiro) {
	
	}
}
