//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Tabuleiro.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class Tabuleiro {
	public Matriz Objeto Celula mMatrizCelula;
	public Matriz Objeto Celula mCelulasAtacadas;
	public boolean bTravaTabuleiro;
	public boolean bTurno;
	public Objeto Jogador oJogador;
	public void getMatrizCelula() {
	
	}
	
	public void setMatrizCelular(Matriz Objeto Celula) {
	
	}
	
	public void getCelulasAtacadas() {
	
	}
	
	public void setCelulasAtacadas(Matriz Objeto Celula) {
	
	}
	
	public void getTravaTabuleiro() {
	
	}
	
	public void setTravaTabuleiro(boolean travaTabuleiro) {
	
	}
	
	public void getTurno() {
	
	}
	
	public void setTurno(boolean turno) {
	
	}
	
	public void getJogador() {
	
	}
	
	public void setJogador(Objeto Jogador) {
	
	}
	
	public void seTabuleiroTravado(Objeto Jogador) {
	
	}
	
	public void seCelulaAtacada(Objeto Celula) {
	
	}
	
	public void encontrarCelula(int x, int y) {
	
	}
}
