//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : TipoCelula.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class TipoCelula {
	public Object embarcacao;
	public Object agua;
	public Object destruido;
}
