//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Usuario.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//


import java.util.*;

public class Usuario {
	public String sLogin;
	public String sSenha;
	public int iId_usuario;
	public String sEmail;
	public String sNacionalidade;
	public int iPontuacao;
	public Date DataCadastro;
	public Date DataCancelamento;
	public boolean bStatusUsuario;
	public void getLogin() {
	
	}
	
	public void setLogin(String login) {
	
	}
	
	public void getSenha() {
	
	}
	
	public void setSenha(String senha) {
	
	}
	
	public void getId_usuario() {
	
	}
	
	public void setId_Usuario(int idUsuario) {
	
	}
	
	public void getEmail() {
	
	}
	
	public void setEmail(String email) {
	
	}
	
	public void getNacionalidade() {
	
	}
	
	public void setNacionalidade(String nacionalidade) {
	
	}
	
	public void getPontuacao() {
	
	}
	
	public void setPontuacao(int pontuacao) {
	
	}
	
	public void getDataCadastro() {
	
	}
	
	public void setDataCadastro(Date dataCadastro) {
	
	}
	
	public void getDataCancelamento() {
	
	}
	
	public void setDataCancelamento(Date dataCancelamento) {
	
	}
	
	public void getStatusUsuario() {
	
	}
	
	public void setStatusUsuario(boolean statusUsuario) {
	
	}
	
	public void logar(String login, String senha) {
	
	}
	
	public void cadastrarUsuario(Objeto Usuario) {
	
	}
	
	public void atualizarUsuario(Objeto Usuario) {
	
	}
	
	public void excluirUsuario(int id_usuario) {
	
	}
	
	public void getUsuario(int id_usuario) {
	
	}
	
	public void getUsuarios(String clausula) {
	
	}
}
