//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Bot.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando,@Marcus
//
//




public class Bot {
	public Objeto Tabuleiro oTabuleiroVirtual;
	public Objeto Celula oUltimaCelulaAtacada;
	public Objeto Celula oProximaCelula;
	public void getTabuleiroVirtual() {
	
	}
	
	public void setTabuleiroVirtual(Objeto Tabuleiro) {
	
	}
	
	public void getUltimoCelulaAtacada() {
	
	}
	
	public void setUltimaCelulaAtacada(Objeto Celula) {
	
	}
	
	public void getProximaCelula() {
	
	}
	
	public void setProximaCelula(Objeto Celula) {
	
	}
	
	public void analisarTabuleiro() {
	
	}
	
	public void analisarJogada() {
	
	}
	
	public void atacar() {
	
	}
	
	public void provocar() {
	
	}
}
