//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Celula.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class Celula {
	public Array aTipoCelula;
	public void getTipoCelula() {
	
	}
	
	public void setTipoCelula(Array tipoCelula) {
	
	}
	
	public void carregarImagem(String tipoCelula) {
	
	}
}
