//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Embarcacao.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class Embarcacao {
	public Array Objeto Celula aListaCelulas;
	public String sNomeEmbarcacao;
	public int iValorEmbarcacao;
	public boolean bNaufragado;
	public void getListaCelulas() {
	
	}
	
	public void setListaCelulas(Array Objeto Celula) {
	
	}
	
	public void getNomeEmbarcacao() {
	
	}
	
	public void setNomeEmbarcacao(String nomeEmbarcacao) {
	
	}
	
	public void getValorEmbarcacao() {
	
	}
	
	public void setValorEmbarcacao(int valorEmbarcacao) {
	
	}
	
	public void getNaufragado() {
	
	}
	
	public void setNaufragado(boolean naufragado) {
	
	}
}
