//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Imagens.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class Imagens {
	public String sLocalImagem;
	public void getLocalImagem() {
	
	}
	
	public void setlocalImagem(String localImagem) {
	
	}
	
	public void carregarImagem() {
	
	}
	
	public void setLocalImagem(Objeto Graphics 2d) {
	
	}
}
}
