//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Ranking.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class Ranking {
	public Array Usuario aListaUsuario;
	public void getListaUsuario() {
	
	}
	
	public void setListaUsuario(Array usuario) {
	
	}
}
