//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Regras.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class Regras {
	public void validarPosicaoNavio(Objeto Embarcacao, Objeto Tabuleiro) {
	
	}
	
	public void validarTiro(Objeto Celula, Objeto Tabuleiro) {
	
	}
	
	public void verificarVencedor(Objeto Tabuleiro) {
	
	}
}
