//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : Servidor.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public class Servidor {
	public Array aListaJogos;
	public Array aListaJogadorOnline;
	public Array aListaJogadorJogando;
	public void getListaJogos() {
	
	}
	
	public void setListaJogos(Array listaJogos) {
	
	}
	
	public void getListaJogadorOnline() {
	
	}
	
	public void setListaJogadorOnline(Array listaJogadorOnlne) {
	
	}
	
	public void getListaJogadorJogando() {
	
	}
	
	public void setListaJogadorJogando(Array listaJogadorJogando) {
	
	}
	
	public void adicionarJogo(Objeto Jogo) {
	
	}
	
	public void removerJogo() {
	
	}
	
	public void registrarLog(String log) {
	
	}
	
	public void verificarJogador(Objeto Jogador) {
	
	}
	
	public void derrubarJogador(Objeto Jogador) {
	
	}
}
