//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : TipoCelula.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//




public enum TipoCelula {
	Embarcacao,
	Agua,
	AreaLivre
}
