package dao;

import java.sql.*;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Seawar
//  @ File Name : ConexaoBD.java
//  @ Date : @06/05/2011
//  @ Author : @Fernando
//
//

public class ConexaoBD {
	private static Connection objConn = null;
	private static final String sSqlDriver = "com.mysql.jdbc.Driver";
	private static final String sSqlPath = "jdbc:mysql://localhost:3306/seawar";
	private static final String sUsuario = "root";
	private static final String sSenha = "root";

	public Connection conectarBanco() throws SQLException {
		try {
			Class.forName(sSqlDriver);
			objConn = DriverManager.getConnection(sSqlPath, sUsuario, sSenha);
		} catch (ClassNotFoundException ex) {
			ex.printStackTrace();
		} catch (SQLException sqlEx) {
			sqlEx.printStackTrace();
		}
		return objConn;
	}

	public void fecharConexaoBanco(Connection objConn) {
		try {
			objConn.close();
		} catch (SQLException sqlEx) {
			sqlEx.printStackTrace();
		}
	}

	// Construtor com declaração default de conexão de banco de dados.
	public ConexaoBD() {

	}

	/**
	 * @return the objConn
	 */
	public Connection getObjConn() {
		return objConn;
	}

	/**
	 * @return the objStatement
	 */
	public Statement getObjStatement() {
		try {
			return getObjConn().createStatement();
		} catch (Exception ex) {
			return null;
		}
	}

	/**
	 * @param objStatement
	 *            the objStatement to set
	 */
	public void setObjStatement(Statement objStatement) {
	}

	public boolean abrirConexao() {
		try {
			objConn = this.conectarBanco();
			this.setObjStatement(this.getObjStatement());
			return true;
		} catch (Exception ex) {
			// aqui podemos pensar em uma hipótese de retorno da exceção de erro
		}
		return false;
	}
}
